"""add item_route and route_option

Revision ID: c5f30b4ec85f
Revises: a3f1c9d47b02
Create Date: 2026-08-12 10:54:30.074096

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5f30b4ec85f'
down_revision = 'a3f1c9d47b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_item_id', sa.Integer(), nullable=False),
    sa.Column('to_item_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('recommended_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['tripday.id'], name=op.f('fk_item_route_day_id_tripday'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_item_id'], ['tripitem.id'], name=op.f('fk_item_route_from_item_id_tripitem'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_item_id'], ['tripitem.id'], name=op.f('fk_item_route_to_item_id_tripitem'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_route'))
    )
    with op.batch_alter_table('item_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_route_day_id'), ['day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_route_from_item_id'), ['from_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_route_to_item_id'), ['to_item_id'], unique=False)

    op.create_table('route_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('line_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['item_route.id'], name=op.f('fk_route_option_route_id_item_route'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_option'))
    )
    with op.batch_alter_table('route_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_option_route_id'), ['route_id'], unique=False)

    # NOTE: Autogenerate also reported nullable/server_default drift on
    # pre-existing `backup.full` and several `user.*` boolean columns. That
    # drift is unrelated to the routes feature (it stems from SQLite reflection
    # of existing tables) and is intentionally NOT included here so this
    # migration's scope is exactly item_route + route_option.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_option_route_id'))

    op.drop_table('route_option')
    with op.batch_alter_table('item_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_route_to_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_route_from_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_route_day_id'))

    op.drop_table('item_route')
    # ### end Alembic commands ###

