"""place multi-image gallery

Revision ID: e7a2c9104bd8
Revises: c5f30b4ec85f
Create Date: 2026-08-12 11:30:00.000000

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e7a2c9104bd8"
down_revision = "c5f30b4ec85f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "placeimagelink",
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["image.id"], name=op.f("fk_placeimagelink_image_id_image"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_placeimagelink_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("place_id", "image_id", name=op.f("pk_placeimagelink")),
    )
    with op.batch_alter_table("placeimagelink", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_placeimagelink_place_id"), ["place_id"], unique=False)

    # Backfill: every Place that already has a cover image_id becomes a
    # one-entry gallery, so the cover is also a gallery member after the
    # migration (mirrors _006_backfill_tripitem_images, but run inside the
    # Alembic transaction rather than as a boot hook). The table is freshly
    # created above, so there are no existing rows to conflict with.
    bind = op.get_bind()
    bind.execute(
        sa.text(
            "INSERT INTO placeimagelink (place_id, image_id) "
            "SELECT id, image_id FROM place WHERE image_id IS NOT NULL"
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("placeimagelink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_placeimagelink_place_id"))

    op.drop_table("placeimagelink")
    # ### end Alembic commands ###
